### ISSUE TITLE
[Feature]: Logic for critical number is less than warning

### ISSUE THREAD

**Issue by martinkonecny** [NETWAYS/check_prometheus#31]
### Describe the feature request

Hi.

I really like your check for prometheus.

I would like to ask you to make a feature that can measure metrics when critical value is lower than warning - when metric value is lower than warning and critical value.

Example:
check_prometheus query --hostname localhost --port 9000 -c 10 -w 20 -q 'metric{instance~"test"}'

This example give me critical output if metric value is 30, but should give OK, because value is not lower than 20 and 10.

Thank you.

Martin Konecny

**Comment by martialblog** [comment]
Hi, thanks for the nice feedback.

Could be that this is already possible. This plugin supports the Nagios style threshold/ranges syntax

https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

**Comment by martinkonecny** [comment]
Great, it works! Thank you so much. Nice job guys!
