### ISSUE TITLE
[Feature]: option to read credentials from file

### ISSUE THREAD

**Issue by zsarosi** [NETWAYS/check_prometheus#40]
### Describe the feature request

Hi
Could you please add an option to read the credentials (username+password) from a file? We use username + password for authentication, but we don't want to include these in the commandline in cleartext, rather store it in a file and let the script read it from there.

**Comment by martialblog** [comment]
Hi, you can set the credentials via ENV variable. For example CHECK_PROMETHEUS_BEARER or CHECK_PROMETHEUS_BASICAUTH

This will avoid setting them in the commandline

**Comment by zsarosi** [comment]
How can I use the ENV variable, if I define a new service template in Icingaweb2 Director module. In our setup we trigger the check_prometheus script over an SSH connection (by_ssh command). In this case I have to set the ENV variable inside the SSH commandline option, but then I again have it in cleartext in the config.

**Comment by martialblog** [comment]
You could set the variable on the machine running the command, and if you are using Icinga you can use the getenv function in the DSL

https://icinga.com/docs/icinga-2/latest/doc/18-library-reference/#getenv

**Comment by zsarosi** [comment]
can you please explain it, how should it work with the DSL in Director, I don't get it, I've never used DSL. I define a service template in Director, and then how should I refer to the getenv function?

**Comment by RincewindsHat** [comment]
AFAIK it is not possible to handover environment variables by using the director. A workaround might be to add the `CheckCommand` via the "classic" text based configuration and expose the variables as fields inside the director.

**Comment by martialblog** [comment]
Hi, 

I just tried this with my own Prometheus instance and it works as expected.

```bash
check_prometheus/ main git checkout v0.2.0

CHECK_PROMETHEUS_BASICAUTH=markus:validpassword go run main.go health -H myprometheus
[OK] - Prometheus Server is Healthy. | statuscode=200

CHECK_PROMETHEUS_BASICAUTH=markus:invalid go run main.go health -H myprometheus
[CRITICAL] - Unauthorized | statuscode=401

env | grep CHECK
CHECK_PROMETHEUS_BASICAUTH=markus:validpassword

go run main.go health -H myprometheus
[OK] - Prometheus Server is Healthy. | statuscode=200
```

I assume the code works as expected

It's probably the variable not being set, but from the info provided I cannot figure out why. Could be something like using `.bashrc` but the execution happens in an environment where this file is not being read.

**Comment by Trabi11** [comment]
So then it must have been fixed between the version I'm using (v.0.1.2) and yours. I'll try with version v0.2.0 :)

Maybe this commit fixed this issue: https://github.com/NETWAYS/check_prometheus/commit/6d1243b6b45bae9eb3184e035df4b7349d8b0857

**Comment by martialblog** [comment]
Yes, this feature was released in https://github.com/NETWAYS/check_prometheus/releases/tag/v0.2.0

**Comment by Trabi11** [comment]
> Yes, this feature was released in https://github.com/NETWAYS/check_prometheus/releases/tag/v0.2.0

Works like expected. Thanks for the Feedback on this @martialblog 

@zsarosi Since we can now use the env variables properly, I see no need to read the credentials from a file. I think you can close the issue

**Comment by martialblog** [comment]
@Trabi11 you're welcome.
