### ISSUE TITLE
Incomplete PerfData

### ISSUE THREAD

**Issue by Crited** [NETWAYS/check_prometheus#7]
Currently the range and the thresholds are missing in the Plugin Output Spec at OPTIONAL PERFDATA, as well as the semicolons, if the values would be empty.

The provided example from the README.md:
```
$ check_prometheus query -q 'go_goroutines' -c 40 -w 27
WARNING - 2 Metrics: 0 Critical - 1 Warning - 1 Ok
 \_[WARNING] go_goroutines{instance="localhost:9090", job="prometheus"} - value: 37
 \_[OK] go_goroutines{instance="node-exporter:9100", job="node-exporter"} - value: 7
 | value_go_goroutines_localhost:9090_prometheus=37 value_go_goroutines_node-exporter:9100_node-exporter=7
```
 
Should return:
```
value_go_goroutines_localhost:9090_prometheus=37;27;40;; value_go_goroutines_node-exporter:9100_node-exporter=7;27;40;;
```

Right now it is like this:
```
'label'=value[UOM]
```

But it has to be like this:
```
'label'=value[UOM];[warn];[crit];[min];[max]
```
https://nagios-plugins.org/doc/guidelines.html

**Comment by martialblog** [comment]
Should be no problem to implement. I'll take care of it

**Comment by RincewindsHat** [comment]
https://www.ietf.org/archive/id/draft-kaestle-monitoring-plugins-interface-00.html#name-performance-data

The semicolons are optional if the respective values are not set.
